title: Meqdad Darwish 

logo: me.jpg 

description: Learner, Developer, Maker and Blogger.

show_downloads: false 

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # SEO plugin

email: meqdad.darweesh@gmail.com 
